-- ============================================================================
-- Flashcards Phase 1 foundations (docs/flashcards-proposal-2026-08-22.md)
--
-- Per-module study decks generated by AI (review-first, kind='flashcards'
-- drafts in module_enhancement_drafts), studied by students under a Leitner
-- 5-box spaced-repetition schedule with server-side box math and streaks.
--
-- Tables:  flashcards, flashcard_reviews, study_streaks
-- RPCs:    record_flashcard_review, get_due_flashcards, get_deck_summaries,
--          apply_flashcard_refresh, revert_flashcard_refresh
-- ============================================================================

-- ── 1. module_enhancement_drafts accepts the new draft kind ─────────────────
alter table public.module_enhancement_drafts
  drop constraint if exists module_enhancement_drafts_kind_check;
alter table public.module_enhancement_drafts
  add constraint module_enhancement_drafts_kind_check
  check (kind in ('accreditation', 'quiz_refresh', 'flashcards'));

-- ── 2. flashcards — one deck per module ─────────────────────────────────────
create table if not exists public.flashcards (
  id          uuid primary key default gen_random_uuid(),
  module_id   uuid not null references public.modules(id) on delete cascade,
  -- Provenance only; a deleted lesson must not delete its cards.
  lesson_id   uuid references public.lessons(id) on delete set null,
  card_type   text not null check (card_type in
    ('term_definition', 'brand_generic', 'drug_stem', 'cloze', 'calculation', 'island_compare')),
  front       text not null check (char_length(front) between 1 and 300),
  back        text not null check (char_length(back) between 1 and 700),
  -- cloze: {answer}; calculation: {answer, tolerance, unit}; others free-form.
  extra       jsonb not null default '{}',
  -- Reviewer provenance, e.g. {block_type: 'key-term', lesson_title: '...'}.
  source      jsonb not null default '{}',
  position    int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists flashcards_module_idx on public.flashcards(module_id, position);

-- updated_at must stamp on EVERY update (the undo guard depends on it).
create or replace function public.flashcards_touch_updated_at()
returns trigger language plpgsql as $trg$
begin new.updated_at := now(); return new; end; $trg$;
drop trigger if exists flashcards_updated_at on public.flashcards;
create trigger flashcards_updated_at before update on public.flashcards
  for each row execute function public.flashcards_touch_updated_at();

alter table public.flashcards enable row level security;

-- Same read posture as quiz_questions: published course, or admin.
drop policy if exists "View flashcards of published courses" on public.flashcards;
create policy "View flashcards of published courses" on public.flashcards
  for select using (
    exists (
      select 1 from public.modules m
      join public.courses c on c.id = m.course_id
      where m.id = flashcards.module_id
        and (c.status = 'published' or is_admin())
    )
  );
drop policy if exists "Admin can insert flashcards" on public.flashcards;
create policy "Admin can insert flashcards" on public.flashcards
  for insert with check (is_admin());
drop policy if exists "Admin can update flashcards" on public.flashcards;
create policy "Admin can update flashcards" on public.flashcards
  for update using (is_admin());
drop policy if exists "Admin can delete flashcards" on public.flashcards;
create policy "Admin can delete flashcards" on public.flashcards
  for delete using (is_admin());

-- ── 3. flashcard_reviews — per-student Leitner state ────────────────────────
-- An abandoned SM-2-style flashcard_reviews table (ease_factor/interval_days,
-- text course_id, 0 rows, no dependents) predates this feature; replace it.
drop table if exists public.flashcard_reviews;
create table public.flashcard_reviews (
  user_id     uuid not null references auth.users(id) on delete cascade,
  card_id     uuid not null references public.flashcards(id) on delete cascade,
  box         smallint not null default 1 check (box between 1 and 5),
  due_at      timestamptz not null default now(),
  reps        int not null default 0,
  lapses      int not null default 0,
  last_grade  text check (last_grade in ('again', 'good', 'easy')),
  updated_at  timestamptz not null default now(),
  primary key (user_id, card_id)
);
create index if not exists flashcard_reviews_due_idx on public.flashcard_reviews(user_id, due_at);

alter table public.flashcard_reviews enable row level security;
-- Students see only their own state. Writes happen exclusively through the
-- SECURITY DEFINER RPC so the Leitner math cannot be gamed client-side.
drop policy if exists "Own flashcard reviews" on public.flashcard_reviews;
create policy "Own flashcard reviews" on public.flashcard_reviews
  for select using (user_id = auth.uid());

-- ── 4. study_streaks — one row per student ──────────────────────────────────
create table if not exists public.study_streaks (
  user_id        uuid primary key references auth.users(id) on delete cascade,
  current_streak int not null default 0,
  longest_streak int not null default 0,
  last_study_date date
);
alter table public.study_streaks enable row level security;
drop policy if exists "Own streak" on public.study_streaks;
create policy "Own streak" on public.study_streaks
  for select using (user_id = auth.uid());

-- ── 5. record_flashcard_review — server-side Leitner + streak ───────────────
create or replace function public.record_flashcard_review(p_card_id uuid, p_grade text)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_uid    uuid := auth.uid();
  v_box    smallint;
  v_due    timestamptz;
  v_today  date := (now() at time zone 'America/Port_of_Spain')::date;
  v_streak study_streaks%rowtype;
begin
  if v_uid is null then raise exception 'Not authenticated'; end if;
  if p_grade not in ('again', 'good', 'easy') then
    raise exception 'grade must be again, good or easy';
  end if;
  -- The card must be visible to the caller (RLS applies via this check).
  if not exists (
    select 1 from flashcards f
    join modules m on m.id = f.module_id
    join courses c on c.id = m.course_id
    where f.id = p_card_id and (c.status = 'published' or is_admin())
  ) then
    raise exception 'Card % not found', p_card_id;
  end if;

  insert into flashcard_reviews as r (user_id, card_id, box, due_at, reps, lapses, last_grade, updated_at)
  values (
    v_uid, p_card_id,
    case p_grade when 'again' then 1 when 'good' then 2 else 3 end,
    now(), 1, case when p_grade = 'again' then 1 else 0 end, p_grade, now()
  )
  on conflict (user_id, card_id) do update set
    box        = case p_grade
                   when 'again' then 1
                   when 'good'  then least(5, r.box + 1)
                   else              least(5, r.box + 2)
                 end,
    reps       = r.reps + 1,
    lapses     = r.lapses + case when p_grade = 'again' then 1 else 0 end,
    last_grade = p_grade,
    updated_at = now()
  returning box into v_box;

  v_due := now() + case v_box
    when 1 then interval '0'
    when 2 then interval '1 day'
    when 3 then interval '3 days'
    when 4 then interval '7 days'
    else interval '21 days' end;
  update flashcard_reviews set due_at = v_due
   where user_id = v_uid and card_id = p_card_id;

  -- One streak credit per calendar day (Port of Spain).
  insert into study_streaks as s (user_id, current_streak, longest_streak, last_study_date)
  values (v_uid, 1, 1, v_today)
  on conflict (user_id) do update set
    current_streak = case
      when s.last_study_date = v_today then s.current_streak
      when s.last_study_date = v_today - 1 then s.current_streak + 1
      else 1 end,
    longest_streak = greatest(s.longest_streak, case
      when s.last_study_date = v_today then s.current_streak
      when s.last_study_date = v_today - 1 then s.current_streak + 1
      else 1 end),
    last_study_date = v_today;

  select * into v_streak from study_streaks where user_id = v_uid;
  return jsonb_build_object('box', v_box, 'due_at', v_due,
                            'current_streak', v_streak.current_streak,
                            'longest_streak', v_streak.longest_streak);
end;
$$;
revoke all on function public.record_flashcard_review(uuid, text) from public, anon;
grant execute on function public.record_flashcard_review(uuid, text) to authenticated;

-- ── 6. get_due_flashcards — one round trip for a study queue ────────────────
-- Due cards first (oldest due first), then up to p_new_limit never-seen cards.
-- p_module_id narrows to one module's deck (the per-module study session).
create or replace function public.get_due_flashcards(
  p_course_id uuid,
  p_module_id uuid default null,
  p_limit int default 40,
  p_new_limit int default 10
)
returns jsonb
language sql security definer set search_path = public as $$
  with visible as (
    select f.*, m.title as module_title, m.order_index as module_order
    from flashcards f
    join modules m on m.id = f.module_id
    join courses c on c.id = m.course_id
    where c.id = p_course_id
      and (p_module_id is null or f.module_id = p_module_id)
      and (c.status = 'published' or is_admin())
  ),
  due as (
    select v.*, r.box, r.due_at, false as is_new
    from visible v
    join flashcard_reviews r on r.card_id = v.id and r.user_id = auth.uid()
    where r.due_at <= now()
    order by r.due_at
    limit greatest(1, least(p_limit, 100))
  ),
  fresh as (
    select v.*, 1::smallint as box, now() as due_at, true as is_new
    from visible v
    where not exists (
      select 1 from flashcard_reviews r
      where r.card_id = v.id and r.user_id = auth.uid()
    )
    order by v.module_order, v.position
    limit greatest(0, least(p_new_limit, 20))
  )
  select coalesce(jsonb_agg(to_jsonb(q) order by q.is_new, q.due_at, q.module_order, q.position), '[]'::jsonb)
  from (select * from due union all select * from fresh) q;
$$;
revoke all on function public.get_due_flashcards(uuid, uuid, int, int) from public, anon;
grant execute on function public.get_due_flashcards(uuid, uuid, int, int) to authenticated;

-- ── 7. get_deck_summaries — per-module totals for sidebar badges ────────────
create or replace function public.get_deck_summaries(p_course_id uuid)
returns jsonb
language sql security definer set search_path = public as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'module_id', s.module_id,
    'total', s.total,
    'due', s.due,
    'new', s.fresh
  )), '[]'::jsonb)
  from (
    select f.module_id,
           count(*) as total,
           count(*) filter (where r.due_at is not null and r.due_at <= now()) as due,
           count(*) filter (where r.card_id is null) as fresh
    from flashcards f
    join modules m on m.id = f.module_id
    join courses c on c.id = m.course_id
    left join flashcard_reviews r on r.card_id = f.id and r.user_id = auth.uid()
    where c.id = p_course_id and (c.status = 'published' or is_admin())
    group by f.module_id
  ) s;
$$;
revoke all on function public.get_deck_summaries(uuid) from public, anon;
grant execute on function public.get_deck_summaries(uuid) to authenticated;

-- ── 8. apply_flashcard_refresh — transactional deck replace with snapshot ───
create or replace function public.apply_flashcard_refresh(p_draft_id uuid, p_keep_ids uuid[] default '{}')
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_draft    module_enhancement_drafts%rowtype;
  v_module   uuid;
  v_payload  jsonb;
  v_snapshot jsonb;
  v_card     jsonb;
  v_lesson   uuid;
  v_pos      int := 0;
  v_kept     int := 0;
  v_deleted  int := 0;
  v_inserted int := 0;
begin
  if not is_admin() then raise exception 'Forbidden: admin only'; end if;
  select * into v_draft from module_enhancement_drafts where id = p_draft_id for update;
  if not found then raise exception 'Draft % not found', p_draft_id; end if;
  if v_draft.kind <> 'flashcards' then raise exception 'Draft is not a flashcard deck'; end if;
  if v_draft.status = 'published' then
    return jsonb_build_object('already_applied', true, 'draft_id', p_draft_id);
  end if;
  if v_draft.status in ('discarded', 'reverted') then raise exception 'Draft was %', v_draft.status; end if;

  v_module  := v_draft.module_id;
  v_payload := v_draft.payload;

  -- Snapshot the current deck for undo. Student review rows for cards deleted
  -- below are cascade-removed and are NOT restorable — undo restores deck
  -- content; per-student progress survives only on kept cards.
  select coalesce(jsonb_agg(to_jsonb(f) order by f.position), '[]'::jsonb)
    into v_snapshot from flashcards f where f.module_id = v_module;
  update module_enhancement_drafts
     set previous_payload = jsonb_build_object('cards', v_snapshot), updated_at = now()
   where id = p_draft_id;

  delete from flashcards
   where module_id = v_module and not (id = any(coalesce(p_keep_ids, '{}'::uuid[])));
  get diagnostics v_deleted = row_count;

  -- Renumber kept cards 1..k preserving relative order.
  with ordered as (
    select id, row_number() over (order by position, created_at) as rn
      from flashcards where module_id = v_module
  )
  update flashcards f set position = o.rn, updated_at = now() from ordered o where f.id = o.id;
  select count(*) into v_kept from flashcards where module_id = v_module;
  v_pos := v_kept;

  for v_card in select * from jsonb_array_elements(coalesce(v_payload->'cards', '[]'::jsonb)) loop
    v_pos := v_pos + 1;
    -- Lesson provenance must belong to this module; anything else drops to null.
    v_lesson := null;
    begin
      v_lesson := nullif(v_card->>'lesson_id', '')::uuid;
    exception when invalid_text_representation then
      v_lesson := null;
    end;
    if v_lesson is not null and not exists (
      select 1 from lessons l where l.id = v_lesson and l.module_id = v_module
    ) then
      v_lesson := null;
    end if;
    insert into flashcards(module_id, lesson_id, card_type, front, back, extra, source, position)
    values (
      v_module, v_lesson,
      v_card->>'card_type',
      left(coalesce(v_card->>'front', ''), 300),
      left(coalesce(v_card->>'back', ''), 700),
      coalesce(v_card->'extra', '{}'::jsonb),
      coalesce(v_card->'source', '{}'::jsonb),
      v_pos
    );
    v_inserted := v_inserted + 1;
  end loop;

  update module_enhancement_drafts
     set status = 'published', published_at = now(), updated_at = now()
   where id = p_draft_id;

  return jsonb_build_object('draft_id', p_draft_id, 'module_id', v_module,
                            'kept', v_kept, 'deleted', v_deleted, 'inserted', v_inserted);
end;
$$;
revoke all on function public.apply_flashcard_refresh(uuid, uuid[]) from public, anon;
grant execute on function public.apply_flashcard_refresh(uuid, uuid[]) to authenticated;

-- ── 9. revert_flashcard_refresh — one-click undo with edit guard ────────────
create or replace function public.revert_flashcard_refresh(p_draft_id uuid)
returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_draft    module_enhancement_drafts%rowtype;
  v_module   uuid;
  v_card     jsonb;
  v_lesson   uuid;
  v_restored int := 0;
begin
  if not is_admin() then raise exception 'Forbidden: admin only'; end if;
  select * into v_draft from module_enhancement_drafts where id = p_draft_id for update;
  if not found then raise exception 'Draft % not found', p_draft_id; end if;
  if v_draft.kind <> 'flashcards' then raise exception 'Draft is not a flashcard deck'; end if;
  if v_draft.status <> 'published' then raise exception 'Draft is not applied (status %)', v_draft.status; end if;
  if v_draft.previous_payload is null then raise exception 'Draft has no snapshot to restore'; end if;

  v_module := v_draft.module_id;

  -- Manual edits after apply win over undo (same rule as revert_quiz_refresh).
  if exists (
    select 1 from flashcards f
    where f.module_id = v_module
      and (f.created_at > v_draft.published_at
           or coalesce(f.updated_at, f.created_at) > v_draft.published_at)
  ) then
    raise exception 'Cards were edited after this deck was applied — undo would destroy manual work. Edit the deck directly instead.';
  end if;

  -- Remove only cards that are NOT in the snapshot (the proposal's inserts).
  -- Kept cards stay in place so their flashcard_reviews rows survive undo.
  delete from flashcards f
   where f.module_id = v_module
     and not exists (
       select 1 from jsonb_array_elements(coalesce(v_draft.previous_payload->'cards', '[]'::jsonb)) s
       where (s->>'id')::uuid = f.id
     );

  -- Upsert every snapshot card back to its pre-apply state (original ids).
  for v_card in select * from jsonb_array_elements(coalesce(v_draft.previous_payload->'cards', '[]'::jsonb)) loop
    -- Lesson may have been deleted since the snapshot; drop the stale ref.
    v_lesson := nullif(v_card->>'lesson_id', '')::uuid;
    if v_lesson is not null and not exists (select 1 from lessons l where l.id = v_lesson) then
      v_lesson := null;
    end if;
    insert into flashcards(id, module_id, lesson_id, card_type, front, back, extra, source, position, created_at, updated_at)
    values (
      (v_card->>'id')::uuid,
      v_module,
      v_lesson,
      v_card->>'card_type',
      v_card->>'front',
      v_card->>'back',
      coalesce(v_card->'extra', '{}'::jsonb),
      coalesce(v_card->'source', '{}'::jsonb),
      coalesce((v_card->>'position')::int, 0),
      coalesce((v_card->>'created_at')::timestamptz, now()),
      coalesce((v_card->>'updated_at')::timestamptz, now())
    )
    on conflict (id) do update set
      lesson_id  = excluded.lesson_id,
      card_type  = excluded.card_type,
      front      = excluded.front,
      back       = excluded.back,
      extra      = excluded.extra,
      source     = excluded.source,
      position   = excluded.position,
      updated_at = excluded.updated_at;
    v_restored := v_restored + 1;
  end loop;

  update module_enhancement_drafts
     set status = 'reverted', updated_at = now()
   where id = p_draft_id;

  return jsonb_build_object('draft_id', p_draft_id, 'module_id', v_module, 'restored', v_restored);
end;
$$;
revoke all on function public.revert_flashcard_refresh(uuid) from public, anon;
grant execute on function public.revert_flashcard_refresh(uuid) to authenticated;
